#include <QIdentityProxyModel>
#include <QSortFilterProxyModel>
#include <QAbstractTableModel>
#include <QIcon>
#include <QStringBuilder>
#include <QtDebug>
#include <QStyledItemDelegate>
#include <QPainter>
#include <QPainterPath>
#include <QComboBox>
#include <QColumnView>
#include <QMenu>
#include <QTableView>
#include <QHeaderView>
#include <QScrollBar>
#include <QMouseEvent>
#include <QWidget>
#include <QVBoxLayout>
#include <QGridLayout>
#include <QString>
#include <QStringList>
#include <QFontDatabase>
#include <QFileInfo>
#include <QApplication>
#include <QRegularExpression>
#include <QMainWindow>
#include <QToolBar>
#include <QToolButton>
#include <QSplashScreen>
#include <QProgressBar>
#include <QLabel>
#include <QTimer>
#include <QJsonDocument>
#include <QJsonObject>
#include <QSettings>
#include <QObject>
#include <QGraphicsObject>
#include <QPoint>
#include <QGraphicsDropShadowEffect>
#include <QGraphicsSceneMouseEvent>
#include <QGraphicsTextItem>
#include <QGraphicsSvgItem>
#include <QGraphicsScene>
#include <QGraphicsRectItem>
#include <QGraphicsView>
#include <QGraphicsItemGroup>
#include <QGraphicsSceneHoverEvent>
#include <QGestureEvent>
#include <QColor>
#include <QRegExp>
#include <QDir>
#include <QProcess>
#include <QMessageBox>
#include <QStyleFactory>
#include <QDoubleSpinBox>
#include <QLineEdit>
#include <QFocusEvent>
#include <QSpinBox>
#include <QFontMetrics>
#include <QColorDialog>
#include <QHBoxLayout>
#include <QDockWidget>
#include <QLocale>
#include <QtMath>
#include <QStackedWidget>
#include <QStyleOptionFrame>
#include <QFileDialog>
#include <QListWidget>
#include <QDropEvent>
#include <QTextEdit>
#include <QDialog>
#include <QtCore/QVariant>
#include <QtWidgets/QAction>
#include <QtWidgets/QApplication>
#include <QtWidgets/QButtonGroup>
#include <QtWidgets/QHBoxLayout>
#include <QtWidgets/QHeaderView>
#include <QtWidgets/QLabel>
#include <QtWidgets/QSpacerItem>
#include <QtWidgets/QToolButton>
#include <QtWidgets/QWidget>
#include <QSpacerItem>
#include <QPushButton>
#include <QDesktopServices>
#include <QFormLayout>
#include <QCheckBox>
#include <QSplitter>
#include <QShowEvent>
#include <QHideEvent>
#include <QUrl>
#include <QClipboard>
#include <QScrollArea>
#include <QRegExpValidator>
#include <QShortcut>
#include <QDateTimeEdit>
#include <QDateEdit>
#include <QInputDialog>
#include <QPlainTextEdit>
#include <QDateTime>
#include <QUuid>
#include <QPaintEvent>
#include <QStylePainter>
#include <QJsonArray>
#include <QDeadlineTimer>
#include <QThread>
#include <QSystemTrayIcon>
#include <QFile>
#include <QVariant>
#include <QtGlobal>
#include <QErrorMessage>
#include <QNetworkAccessManager>
#include <QNetworkReply>
#include <QStaticText>
#include <QTextBrowser>

#include <cmath>
