#include "language-utils.h"

LanguageList::LanguageList(QObject *parent): QObject(parent)
{
    //639-2, 639-3, 639-1, English Name, Native Name
    _languages << QStringList( { "aar","aar","aa","Afar","Qafaraf" } );
    _languages << QStringList( { "abk","abk","ab","Abkhazian","Аҧсуа бызшәа" } );
    _languages << QStringList( { "ace","ace", "","Achinese","بهسا اچيه" } );
    _languages << QStringList( { "ach","ach", "","Acoli","Lwo" } );
    _languages << QStringList( { "ada","ada", "","Adangme","Dangme" } );
    _languages << QStringList( { "ady","ady", "","Adyghe","Адыгабзэ" } );
    _languages << QStringList( { "afa", "", "","Afro-Asiatic languages" } );
    _languages << QStringList( { "afh","afh", "","Afrihili","El-Afrihili" } );
    _languages << QStringList( { "afr","afr","af","Afrikaans","Afrikaans" } );
    _languages << QStringList( { "ain","ain", "","Ainu","アイヌ・イタㇰ" } );
    _languages << QStringList( { "aka","aka","ak","Akan","Akan" } );
    _languages << QStringList( { "akk","akk", "","Akkadian","" } );
    _languages << QStringList( { "sqi","sqi","sq","Albanian","Shqip" } );
    _languages << QStringList( { "alb","sqi","sq","Albanian","Shqip" } );
    _languages << QStringList( { "ale","ale", "","Aleut","Уна́ӈам тунуу́" } );
    _languages << QStringList( { "alg", "", "","Algonquian languages" } );
    _languages << QStringList( { "alt","alt", "","Southern Altai","Алтай тили" } );
    _languages << QStringList( { "amh","amh","am","Amharic","አማርኛ" } );
    _languages << QStringList( { "ang","ang", "","English, Old","Ænglisc" } );
    _languages << QStringList( { "anp","anp", "","Angika" } );
    _languages << QStringList( { "apa", "", "","Apache languages" } );
    _languages << QStringList( { "ara","ara","ar","Arabic","العَرَبِيَّة" } );
    _languages << QStringList( { "arc","arc", "","Official Aramaic (700–300 BCE)" } );
    _languages << QStringList( { "arg","arg","an","Aragonese","aragonés" } );
    _languages << QStringList( { "arm","hye","hy","Armenian","Հայերէն" } );
    _languages << QStringList( { "hye","hye","hy","Armenian","Հայերէն" } );
    _languages << QStringList( { "arn","arn", "","Mapudungun" } );
    _languages << QStringList( { "arp","arp", "","Arapaho","Hinónoʼeitíít" } );
    _languages << QStringList( { "art", "", "","Artificial languages" } );
    _languages << QStringList( { "arw","arw", "","Arawak","Lokono" } );
    _languages << QStringList( { "asm","asm","as","Assamese","অসমীয়া" } );
    _languages << QStringList( { "ast","ast", "","Asturian" } );
    _languages << QStringList( { "ath", "", "","Athapascan languages" } );
    _languages << QStringList( { "aus", "", "","Australian languages" } );
    _languages << QStringList( { "ava","ava","av","Avaric","Магӏарул мацӏ" } );
    _languages << QStringList( { "ave","ave","ae","Avestan" } );
    _languages << QStringList( { "awa","awa", "","Awadhi","अवधी" } );
    _languages << QStringList( { "aym","aym","ay","Aymara","Aymar aru" } );
    _languages << QStringList( { "aze","aze","az","Azerbaijani","Azərbaycan dili" } );
    _languages << QStringList( { "bad", "", "","Banda languages" } );
    _languages << QStringList( { "bai", "", "","Bamileke languages","Bamiléké" } );
    _languages << QStringList( { "bak","bak","ba","Bashkir","Башҡорт теле" } );
    _languages << QStringList( { "bal","bal", "","Baluchi","بلوچی" } );
    _languages << QStringList( { "bam","bam","bm","Bambara","ߓߊߡߊߣߊߣߞߊߣ" } );
    _languages << QStringList( { "ban","ban", "","Balinese","" } );
    _languages << QStringList( { "baq","eus","eu","Basque","euskara" } );
    _languages << QStringList( { "eus","eus","eu","Basque","euskara" } );
    _languages << QStringList( { "bas","bas", "","Basa","Mbene" } );
    _languages << QStringList( { "bat", "", "","Baltic languages" } );
    _languages << QStringList( { "bej","bej", "","Beja" } );
    _languages << QStringList( { "bel","bel","be","Belarusian","Беларуская мова" } );
    _languages << QStringList( { "bem","bem", "","Bemba","Chibemba" } );
    _languages << QStringList( { "ben","ben","bn","Bengali","বাংলা" } );
    _languages << QStringList( { "ber", "", "","Berber languages","Tamaziɣt" } );
    _languages << QStringList( { "bho","bho", "","Bhojpuri","भोजपुरी" } );
    _languages << QStringList( { "bih", "","bh","Bihari languages" } );
    _languages << QStringList( { "bik","bik", "","Bikol" } );
    _languages << QStringList( { "bin","bin", "","Bini" } );
    _languages << QStringList( { "bis","bis","bi","Bislama" } );
    _languages << QStringList( { "bla","bla", "","Siksika","ᓱᖽᐧᖿ" } );
    _languages << QStringList( { "bnt", "", "","Bantu (Other)" } );
    _languages << QStringList( { "bod","bod","bo","Tibetan","བོད་སྐད་" } );
    _languages << QStringList( { "tib","bod","bo","Tibetan","བོད་སྐད་" } );
    _languages << QStringList( { "bos","bos","bs","Bosnian","bosanski" } );
    _languages << QStringList( { "bra","bra", "","Braj" } );
    _languages << QStringList( { "bre","bre","br","Breton","Brezhoneg" } );
    _languages << QStringList( { "btk", "", "","Batak languages" } );
    _languages << QStringList( { "bua","bua", "","Buriat","буряад хэлэн" } );
    _languages << QStringList( { "bug","bug", "","Buginese","ᨅᨔ ᨕᨘᨁᨗ" } );
    _languages << QStringList( { "bul","bul","bg","Bulgarian","български език" } );
    _languages << QStringList( { "mya","mya","my","Burmese","မြန်မာစာ" } );
    _languages << QStringList( { "bur","mya","my","Burmese","မြန်မာစာ" } );
    _languages << QStringList( { "byn","byn", "","Blin" } );
    _languages << QStringList( { "cad","cad", "","Caddo","Hasí:nay" } );
    _languages << QStringList( { "cai", "", "","Central American Indian languages" } );
    _languages << QStringList( { "car","car", "","Galibi Carib","Kari'nja" } );
    _languages << QStringList( { "cat","cat","ca","Catalan" } );
    _languages << QStringList( { "cau", "", "","Caucasian languages" } );
    _languages << QStringList( { "ceb","ceb", "","Cebuano","Sinugbuanong Binisayâ" } );
    _languages << QStringList( { "cel", "", "","Celtic languages" } );
    _languages << QStringList( { "ces","ces","cs","Czech","čeština" } );
    _languages << QStringList( { "cha","cha","ch","Chamorro","Finu' Chamoru" } );
    _languages << QStringList( { "chb","chb", "","Chibcha","Muysccubun" } );
    _languages << QStringList( { "che","che","ce","Chechen","Нохчийн мотт" } );
    _languages << QStringList( { "chg","chg", "","Chagatai","جغتای" } );
    _languages << QStringList( { "chi","zho","zh","Chinese","中文" } );
    _languages << QStringList( { "chk","chk", "","Chuukese" } );
    _languages << QStringList( { "chm","chm", "","Mari","марий йылме" } );
    _languages << QStringList( { "chn","chn", "","Chinook jargon","chinuk wawa" } );
    _languages << QStringList( { "cho","cho", "","Choctaw","Chahta'" } );
    _languages << QStringList( { "chp","chp", "","Chipewyan" } );
    _languages << QStringList( { "chr","chr", "","Cherokee","ᏣᎳᎩ ᎦᏬᏂᎯᏍᏗ" } );
    _languages << QStringList( { "chu","chu","cu","Church Slavic" } );
    _languages << QStringList( { "chv","chv","cv","Chuvash","Чӑвашла" } );
    _languages << QStringList( { "chy","chy", "","Cheyenne","Tsėhésenėstsestȯtse" } );
    _languages << QStringList( { "cmc", "", "","Chamic languages" } );
    _languages << QStringList( { "cnr","cnr", "","Montenegrin","crnogorski / црногорски" } );
    _languages << QStringList( { "cop","cop", "","Coptic","ϯⲙⲉⲑⲣⲉⲙⲛ̀ⲭⲏⲙⲓ" } );
    _languages << QStringList( { "cor","cor","kw","Cornish","Kernowek" } );
    _languages << QStringList( { "cos","cos","co","Corsican","Corsu" } );
    _languages << QStringList( { "cpe", "", "","Creoles and pidgins, English based" } );
    _languages << QStringList( { "cpf", "", "","Creoles and pidgins, French-based" } );
    _languages << QStringList( { "cpp", "", "","Creoles and pidgins, Portuguese-based" } );
    _languages << QStringList( { "cre","cre","cr","Cree" } );
    _languages << QStringList( { "crh","crh", "","Crimean Tatar" } );
    _languages << QStringList( { "crp", "", "","Creoles and pidgins" } );
    _languages << QStringList( { "csb","csb", "","Kashubian","Kaszëbsczi jãzëk" } );
    _languages << QStringList( { "cus", "", "","Cushitic languages" } );
    _languages << QStringList( { "cym","cym","cy","Welsh","Cymraeg" } );
    _languages << QStringList( { "cze","ces","cs","Czech","čeština" } );
    _languages << QStringList( { "dak","dak", "","Dakota","Dakhótiyapi" } );
    _languages << QStringList( { "dan","dan","da","Danish","dansk" } );
    _languages << QStringList( { "dar","dar", "","Dargwa","дарган мез" } );
    _languages << QStringList( { "day", "", "","Land Dayak languages" } );
    _languages << QStringList( { "del","del", "","Delaware" } );
    _languages << QStringList( { "den","den", "","Slave (Athapascan)","Dene K'e" } );
    _languages << QStringList( { "deu","deu","de","German","Deutsch" } );
    _languages << QStringList( { "dgr","dgr", "","Dogrib","डोगरी" } );
    _languages << QStringList( { "din","din", "","Dinka","Thuɔŋjäŋ" } );
    _languages << QStringList( { "div","div","dv","Divehi" } );
    _languages << QStringList( { "doi","doi", "","Dogri","डोगरी" } );
    _languages << QStringList( { "dra", "", "","Dravidian languages" } );
    _languages << QStringList( { "dsb","dsb", "","Lower Sorbian","Dolnoserbski" } );
    _languages << QStringList( { "dua","dua", "","Duala" } );
    _languages << QStringList( { "dum","dum", "","Dutch, Middle (ca. 1050–1350)" } );
    _languages << QStringList( { "dut","nld","nl","Dutch" } );
    _languages << QStringList( { "dyu","dyu", "","Dyula","Julakan" } );
    _languages << QStringList( { "dzo","dzo","dz","Dzongkha","རྫོང་ཁ་" } );
    _languages << QStringList( { "efi","efi", "","Efik" } );
    _languages << QStringList( { "egy","egy", "","Egyptian (Ancient)" } );
    _languages << QStringList( { "eka","eka", "","Ekajuk" } );
    _languages << QStringList( { "ell","ell","el","Greek, Modern (1453–)","Νέα Ελληνικά" } );
    _languages << QStringList( { "elx","elx", "","Elamite" } );
    _languages << QStringList( { "eng","eng","en","English","English" } );
    _languages << QStringList( { "enm","enm", "","English, Middle (1100–1500)" } );
    _languages << QStringList( { "epo","epo","eo","Esperanto","Esperanto" } );
    _languages << QStringList( { "est","est","et","Estonian","eesti keel" } );
    _languages << QStringList( { "eus","eus","eu","Basque","euskara" } );
    _languages << QStringList( { "ewe","ewe","ee","Ewe","Èʋegbe" } );
    _languages << QStringList( { "ewo","ewo", "","Ewondo" } );
    _languages << QStringList( { "fan","fan", "","Fang" } );
    _languages << QStringList( { "fao","fao","fo","Faroese","føroyskt" } );
    _languages << QStringList( { "fas","fas","fa","Persian","فارسی" } );
    _languages << QStringList( { "fat","fat", "","Fanti","Mfantse" } );
    _languages << QStringList( { "fij","fij","fj","Fijian","Na Vosa Vakaviti" } );
    _languages << QStringList( { "fil","fil", "","Filipino" } );
    _languages << QStringList( { "fin","fin","fi","Finnish","suomen kieli" } );
    _languages << QStringList( { "fiu", "", "","Finno-Ugrian languages" } );
    _languages << QStringList( { "fon","fon", "","Fon","Fon gbè" } );
    _languages << QStringList( { "fra","fra","fr","French","français" } );
    _languages << QStringList( { "fre","fra","fr","French","français" } );
    _languages << QStringList( { "frm","frm", "","French, Middle (ca. 1400–1600)","françois" } );
    _languages << QStringList( { "fro","fro", "","French, Old (842–ca. 1400)","Franceis" } );
    _languages << QStringList( { "frr","frr", "","Northern Frisian","Frasch" } );
    _languages << QStringList( { "frs","frs", "","Eastern Frisian","Seeltersk" } );
    _languages << QStringList( { "fry","fry","fy","Western Frisian","Frysk" } );
    _languages << QStringList( { "ful","ful","ff","Fulah","Fulfulde" } );
    _languages << QStringList( { "fur","fur", "","Friulian","Furlan" } );
    _languages << QStringList( { "gaa","gaa", "","Ga","Gã" } );
    _languages << QStringList( { "gay","gay", "","Gayo","Basa Gayo" } );
    _languages << QStringList( { "gba","gba", "","Gbaya" } );
    _languages << QStringList( { "gem", "", "","Germanic languages" } );
    _languages << QStringList( { "geo","kat","ka","Georgian","ქართული" } );
    _languages << QStringList( { "ger","deu","de","German","Deutsch" } );
    _languages << QStringList( { "gez","gez", "","Geez","ግዕዝ" } );
    _languages << QStringList( { "gil","gil", "","Gilbertese","Taetae ni Kiribati" } );
    _languages << QStringList( { "gla","gla","gd","Gaelic" } );
    _languages << QStringList( { "gle","gle","ga","Irish","Gaeilge" } );
    _languages << QStringList( { "glg","glg","gl","Galician","galego" } );
    _languages << QStringList( { "glv","glv","gv","Manx","Gaelg" } );
    _languages << QStringList( { "gmh","gmh", "","German, Middle High (ca. 1050–1500)","Diutsch" } );
    _languages << QStringList( { "goh","goh", "","German, Old High (ca. 750–1050)","Diutisk" } );
    _languages << QStringList( { "gon","gon", "","Gondi" } );
    _languages << QStringList( { "gor","gor", "","Gorontalo","Bahasa Hulontalo" } );
    _languages << QStringList( { "got","got", "","Gothic" } );
    _languages << QStringList( { "grb","grb", "","Grebo" } );
    _languages << QStringList( { "grc","grc", "","Greek, Ancient (to 1453)","Ἑλληνική" } );
    _languages << QStringList( { "gre","ell","el","Greek, Modern (1453–)","Νέα Ελληνικά" } );
    _languages << QStringList( { "grn","grn","gn","Guarani","Avañe'ẽ" } );
    _languages << QStringList( { "gsw","gsw", "","Swiss German" } );
    _languages << QStringList( { "guj","guj","gu","Gujarati","ગુજરાતી" } );
    _languages << QStringList( { "gwi","gwi", "","Gwich'in","Dinjii Zhu’ Ginjik" } );
    _languages << QStringList( { "hai","hai", "","Haida","X̱aat Kíl" } );
    _languages << QStringList( { "hat","hat","ht","Haitian" } );
    _languages << QStringList( { "hau","hau","ha","Hausa","Harshen Hausa" } );
    _languages << QStringList( { "haw","haw", "","Hawaiian","ʻŌlelo Hawaiʻi" } );
    _languages << QStringList( { "heb","heb","he","Hebrew","עברית" } );
    _languages << QStringList( { "her","her","hz","Herero","Otjiherero" } );
    _languages << QStringList( { "hil","hil", "","Hiligaynon","Ilonggo" } );
    _languages << QStringList( { "him", "", "","Himachali languages" } );
    _languages << QStringList( { "hin","hin","hi","Hindi","हिन्दी" } );
    _languages << QStringList( { "hit","hit", "","Hittite","𒉈𒅆𒇷" } );
    _languages << QStringList( { "hmn","hmn", "","Hmong" } );
    _languages << QStringList( { "hmo","hmo","ho","Hiri Motu" } );
    _languages << QStringList( { "hrv","hrv","hr","Croatian","hrvatski" } );
    _languages << QStringList( { "hsb","hsb", "","Upper Sorbian","hornjoserbšćina" } );
    _languages << QStringList( { "hun","hun","hu","Hungarian","magyar nyelv" } );
    _languages << QStringList( { "hup","hup", "","Hupa","Na:tinixwe Mixine:whe'" } );
    _languages << QStringList( { "hye / arm","hye","hy","Armenian","Հայերէն" } );
    _languages << QStringList( { "iba","iba", "","Iban","Jaku Iban" } );
    _languages << QStringList( { "ibo","ibo","ig","Igbo","Asụsụ Igbo" } );
    _languages << QStringList( { "ice","isl","is","Icelandic","íslenska" } );
    _languages << QStringList( { "ido","ido","io","Ido" } );
    _languages << QStringList( { "iii","iii","ii","Sichuan Yi" } );
    _languages << QStringList( { "ijo", "", "","Ijo languages","Ịjọ" } );
    _languages << QStringList( { "iku","iku","iu","Inuktitut","ᐃᓄᒃᑎᑐᑦ" } );
    _languages << QStringList( { "ile","ile","ie","Interlingue" } );
    _languages << QStringList( { "ilo","ilo", "","Iloko","Pagsasao nga Ilokano" } );
    _languages << QStringList( { "ina","ina","ia","Interlingua (International Auxiliary Language Association)" } );
    _languages << QStringList( { "inc", "", "","Indic languages" } );
    _languages << QStringList( { "ind","ind","id","Indonesian","bahasa Indonesia" } );
    _languages << QStringList( { "ine", "", "","Indo-European languages" } );
    _languages << QStringList( { "inh","inh", "","Ingush","ГӀалгӀай мотт" } );
    _languages << QStringList( { "ipk","ipk","ik","Inupiaq","Iñupiaq" } );
    _languages << QStringList( { "ira", "", "","Iranian languages" } );
    _languages << QStringList( { "iro", "", "","Iroquoian languages" } );
    _languages << QStringList( { "isl","isl","is","Icelandic","íslenska" } );
    _languages << QStringList( { "ita","ita","it","Italian","italiano" } );
    _languages << QStringList( { "jav","jav","jv","Javanese","ꦧꦱꦗꦮ" } );
    _languages << QStringList( { "jbo","jbo", "","Lojban","la .lojban." } );
    _languages << QStringList( { "jpn","jpn","ja","Japanese","日本語" } );
    _languages << QStringList( { "jpr","jpr", "","Judeo-Persian","Dzhidi" } );
    _languages << QStringList( { "jrb","jrb", "","Judeo-Arabic","عربية يهودية / ערבית יהודית" } );
    _languages << QStringList( { "kaa","kaa", "","Kara-Kalpak","Qaraqalpaq tili" } );
    _languages << QStringList( { "kab","kab", "","Kabyle","Tamaziɣt Taqbaylit" } );
    _languages << QStringList( { "kac","kac", "","Kachin" } );
    _languages << QStringList( { "kal","kal","kl","Kalaallisut" } );
    _languages << QStringList( { "kam","kam", "","Kamba" } );
    _languages << QStringList( { "kan","kan","kn","Kannada","ಕನ್ನಡ" } );
    _languages << QStringList( { "kar", "", "","Karen languages" } );
    _languages << QStringList( { "kas","kas","ks","Kashmiri","कॉशुर / كأشُر" } );
    _languages << QStringList( { "kat","kat","ka","Georgian","ქართული" } );
    _languages << QStringList( { "kau","kau","kr","Kanuri" } );
    _languages << QStringList( { "kaw","kaw", "","Kawi","ꦧꦱꦗꦮ" } );
    _languages << QStringList( { "kaz","kaz","kk","Kazakh","қазақ тілі / qazaq tili" } );
    _languages << QStringList( { "kbd","kbd", "","Kabardian","Адыгэбзэ (Къэбэрдейбзэ)" } );
    _languages << QStringList( { "kha","kha", "","Khasi","কা কতিয়েন খাশি" } );
    _languages << QStringList( { "khi", "", "","Khoisan languages" } );
    _languages << QStringList( { "khm","khm","km","Central Khmer","ភាសាខ្មែរ" } );
    _languages << QStringList( { "kho","kho", "","Khotanese" } );
    _languages << QStringList( { "kik","kik","ki","Kikuyu" } );
    _languages << QStringList( { "kin","kin","rw","Kinyarwanda" } );
    _languages << QStringList( { "kir","kir","ky","Kirghiz" } );
    _languages << QStringList( { "kmb","kmb", "","Kimbundu" } );
    _languages << QStringList( { "kok","kok", "","Konkani","कोंकणी" } );
    _languages << QStringList( { "kom","kom","kv","Komi","Коми кыв" } );
    _languages << QStringList( { "kon","kon","kg","Kongo" } );
    _languages << QStringList( { "kor","kor","ko","Korean","한국어" } );
    _languages << QStringList( { "kos","kos", "","Kosraean" } );
    _languages << QStringList( { "kpe","kpe", "","Kpelle","Kpɛlɛwoo" } );
    _languages << QStringList( { "krc","krc", "","Karachay-Balkar","Къарачай-Малкъар тил" } );
    _languages << QStringList( { "krl","krl", "","Karelian","karjal" } );
    _languages << QStringList( { "kro", "", "","Kru languages" } );
    _languages << QStringList( { "kru","kru", "","Kurukh","कुड़ुख़" } );
    _languages << QStringList( { "kua","kua","kj","Kuanyama" } );
    _languages << QStringList( { "kum","kum", "","Kumyk","къумукъ тил/qumuq til" } );
    _languages << QStringList( { "kur","kur","ku","Kurdish","Kurdî / کوردی" } );
    _languages << QStringList( { "kut","kut", "","Kutenai" } );
    _languages << QStringList( { "lad","lad", "","Ladino","Judeo-español" } );
    _languages << QStringList( { "lah","lah", "","Lahnda","بھارت کا" } );
    _languages << QStringList( { "lam","lam", "","Lamba" } );
    _languages << QStringList( { "lao","lao","lo","Lao","ພາສາລາວ" } );
    _languages << QStringList( { "lat","lat","la","Latin","Lingua latīna" } );
    _languages << QStringList( { "lav","lav","lv","Latvian","Latviešu valoda" } );
    _languages << QStringList( { "lez","lez", "","Lezghian","Лезги чӏал" } );
    _languages << QStringList( { "lim","lim","li","Limburgan" } );
    _languages << QStringList( { "lin","lin","ln","Lingala" } );
    _languages << QStringList( { "lit","lit","lt","Lithuanian","lietuvių kalba" } );
    _languages << QStringList( { "lol","lol", "","Mongo","Lomongo" } );
    _languages << QStringList( { "loz","loz", "","Lozi" } );
    _languages << QStringList( { "ltz","ltz","lb","Luxembourgish" } );
    _languages << QStringList( { "lua","lua", "","Luba-Lulua","Tshiluba" } );
    _languages << QStringList( { "lub","lub","lu","Luba-Katanga","Kiluba" } );
    _languages << QStringList( { "lug","lug","lg","Ganda","Luganda" } );
    _languages << QStringList( { "lui","lui", "","Luiseno","Cham'teela" } );
    _languages << QStringList( { "lun","lun", "","Lunda","Chilunda" } );
    _languages << QStringList( { "luo","luo", "","Luo (Kenya and Tanzania)","Dholuo" } );
    _languages << QStringList( { "lus","lus", "","Lushai","Mizo ṭawng" } );
    _languages << QStringList( { "mac / mkd","mkd","mk","Macedonian","македонски јазик" } );
    _languages << QStringList( { "mad","mad", "","Madurese","Madhura" } );
    _languages << QStringList( { "mag","mag", "","Magahi","मगही" } );
    _languages << QStringList( { "mah","mah","mh","Marshallese","Kajin M̧ajeļ" } );
    _languages << QStringList( { "mai","mai", "","Maithili","मैथिली" } );
    _languages << QStringList( { "mak","mak", "","Makasar","Basa Mangkasara' / ᨅᨔ ᨆᨀᨔᨑ" } );
    _languages << QStringList( { "mal","mal","ml","Malayalam","മലയാളം" } );
    _languages << QStringList( { "man","man", "","Mandingo","Mandi'nka kango" } );
    _languages << QStringList( { "mao","mri","mi","Maori","Te Reo Māori" } );
    _languages << QStringList( { "map", "", "","Austronesian languages" } );
    _languages << QStringList( { "mar","mar","mr","Marathi","मराठी" } );
    _languages << QStringList( { "mas","mas", "","Masai","ɔl" } );
    _languages << QStringList( { "may","msa","ms","Malay","Bahasa Melayu" } );
    _languages << QStringList( { "mdf","mdf", "","Moksha","мокшень кяль" } );
    _languages << QStringList( { "mdr","mdr", "","Mandar" } );
    _languages << QStringList( { "men","men", "","Mende","Mɛnde yia" } );
    _languages << QStringList( { "mga","mga", "","Irish, Middle (900–1200)","Gaoidhealg" } );
    _languages << QStringList( { "mic","mic", "","Mi'kmaq" } );
    _languages << QStringList( { "min","min", "","Minangkabau","Baso Minang" } );
    _languages << QStringList( { "mis","mis", "","Uncoded languages" } );
    _languages << QStringList( { "mkd","mkd","mk","Macedonian","македонски јазик" } );
    _languages << QStringList( { "mkh", "", "","Mon-Khmer languages" } );
    _languages << QStringList( { "mlg","mlg","mg","Malagasy" } );
    _languages << QStringList( { "mlt","mlt","mt","Maltese","Malti" } );
    _languages << QStringList( { "mnc","mnc", "","Manchu","ᠮᠠᠨᠵᡠ ᡤᡳᠰᡠᠨ" } );
    _languages << QStringList( { "mni","mni", "","Manipuri" } );
    _languages << QStringList( { "mno", "", "","Manobo languages" } );
    _languages << QStringList( { "moh","moh", "","Mohawk","Kanien’kéha" } );
    _languages << QStringList( { "mon","mon","mn","Mongolian","монгол хэл" } );
    _languages << QStringList( { "mos","mos", "","Mossi","Mooré" } );
    _languages << QStringList( { "mri","mri","mi","Maori","Te Reo Māori" } );
    _languages << QStringList( { "msa","msa","ms","Malay","Bahasa Melayu" } );
    _languages << QStringList( { "mul","mul", "","Multiple languages" } );
    _languages << QStringList( { "mun", "", "","Munda languages" } );
    _languages << QStringList( { "mus","mus", "","Creek","Mvskoke" } );
    _languages << QStringList( { "mwl","mwl", "","Mirandese","mirandés" } );
    _languages << QStringList( { "mwr","mwr", "","Marwari","मारवाड़ी" } );
    _languages << QStringList( { "mya","mya","my","Burmese","မြန်မာစာ" } );
    _languages << QStringList( { "myn", "", "","Mayan languages" } );
    _languages << QStringList( { "myv","myv", "","Erzya","эрзянь кель" } );
    _languages << QStringList( { "nah", "", "","Nahuatl languages" } );
    _languages << QStringList( { "nai", "", "","North American Indian languages" } );
    _languages << QStringList( { "nap","nap", "","Neapolitan","napulitano" } );
    _languages << QStringList( { "nau","nau","na","Nauru","dorerin Naoero" } );
    _languages << QStringList( { "nav","nav","nv","Navajo" } );
    _languages << QStringList( { "nbl","nbl","nr","Ndebele, South" } );
    _languages << QStringList( { "nde","nde","nd","Ndebele, North" } );
    _languages << QStringList( { "ndo","ndo","ng","Ndonga","ndonga" } );
    _languages << QStringList( { "nds","nds", "","Low German" } );
    _languages << QStringList( { "nep","nep","ne","Nepali","नेपाली भाषा" } );
    _languages << QStringList( { "new","new", "","Nepal Bhasa" } );
    _languages << QStringList( { "nia","nia", "","Nias","Li Niha" } );
    _languages << QStringList( { "nic", "", "","Niger-Kordofanian languages" } );
    _languages << QStringList( { "niu","niu", "","Niuean","ko e vagahau Niuē" } );
    _languages << QStringList( { "nld","nld","nl","Dutch" } );
    _languages << QStringList( { "nno","nno","nn","Norwegian Nynorsk" } );
    _languages << QStringList( { "nob","nob","nb","Bokmål, Norwegian" } );
    _languages << QStringList( { "nog","nog", "","Nogai","Ногай тили" } );
    _languages << QStringList( { "non","non", "","Norse, Old","Dǫnsk tunga" } );
    _languages << QStringList( { "nor","nor","no","Norwegian","norsk" } );
    _languages << QStringList( { "nqo","nqo", "","N'Ko" } );
    _languages << QStringList( { "nso","nso", "","Pedi" } );
    _languages << QStringList( { "nub", "", "","Nubian languages","لغات نوبية" } );
    _languages << QStringList( { "nwc","nwc", "","Classical Newari" } );
    _languages << QStringList( { "nya","nya","ny","Chichewa" } );
    _languages << QStringList( { "nym","nym", "","Nyamwezi" } );
    _languages << QStringList( { "nyn","nyn", "","Nyankole" } );
    _languages << QStringList( { "nyo","nyo", "","Nyoro","Runyoro" } );
    _languages << QStringList( { "nzi","nzi", "","Nzima" } );
    _languages << QStringList( { "oci","oci","oc","Occitan (post 1500)" } );
    _languages << QStringList( { "oji","oji","oj","Ojibwa" } );
    _languages << QStringList( { "ori","ori","or","Oriya","ଓଡ଼ିଆ" } );
    _languages << QStringList( { "orm","orm","om","Oromo","Afaan Oromoo" } );
    _languages << QStringList( { "osa","osa", "","Osage","Wazhazhe ie / 𐓏𐓘𐓻𐓘𐓻𐓟 𐒻𐓟" } );
    _languages << QStringList( { "oss","oss","os","Ossetian" } );
    _languages << QStringList( { "ota","ota", "","Turkish, Ottoman (1500–1928)","لسان عثمانى / lisân-ı Osmânî" } );
    _languages << QStringList( { "oto", "", "","Otomian languages" } );
    _languages << QStringList( { "paa", "", "","Papuan languages" } );
    _languages << QStringList( { "pag","pag", "","Pangasinan","Salitan Pangasinan" } );
    _languages << QStringList( { "pal","pal", "","Pahlavi","Pārsīk" } );
    _languages << QStringList( { "pam","pam", "","Pampanga" } );
    _languages << QStringList( { "pan","pan","pa","Panjabi" } );
    _languages << QStringList( { "pap","pap", "","Papiamento","Papiamentu" } );
    _languages << QStringList( { "pau","pau", "","Palauan","a tekoi er a Belau" } );
    _languages << QStringList( { "peo","peo", "","Persian, Old (ca. 600–400 B.C.)" } );
    _languages << QStringList( { "per","fas","fa","Persian","فارسی" } );
    _languages << QStringList( { "phi", "", "","Philippine languages" } );
    _languages << QStringList( { "phn","phn", "","Phoenician","𐤃𐤁𐤓𐤉𐤌 𐤊𐤍𐤏𐤍𐤉𐤌" } );
    _languages << QStringList( { "pli","pli","pi","Pali","Pāli" } );
    _languages << QStringList( { "pol","pol","pl","Polish","Język polski" } );
    _languages << QStringList( { "pon","pon", "","Pohnpeian" } );
    _languages << QStringList( { "por","por","pt","Portuguese","português" } );
    _languages << QStringList( { "pra", "", "","Prakrit languages" } );
    _languages << QStringList( { "pro","pro", "","Provençal, Old (to 1500)" } );
    _languages << QStringList( { "pus","pus","ps","Pushto" } );
    _languages << QStringList( { "qaa-qtz","qaa-qtz", "","Reserved for local use" } );
    _languages << QStringList( { "que","que","qu","Quechua","Runa simi" } );
    _languages << QStringList( { "raj","raj", "","Rajasthani","राजस्थानी" } );
    _languages << QStringList( { "rap","rap", "","Rapanui","Vananga rapa nui" } );
    _languages << QStringList( { "rar","rar", "","Rarotongan" } );
    _languages << QStringList( { "roa", "", "","Romance languages" } );
    _languages << QStringList( { "roh","roh","rm","Romansh","Rumantsch" } );
    _languages << QStringList( { "rom","rom", "","Romany","romani čhib" } );
    _languages << QStringList( { "ron","ron","ro","Romanian" } );
    _languages << QStringList( { "rum","ron","ro","Romanian" } );
    _languages << QStringList( { "run","run","rn","Rundi","Ikirundi" } );
    _languages << QStringList( { "rup","rup", "","Aromanian" } );
    _languages << QStringList( { "rus","rus","ru","Russian","русский язык" } );
    _languages << QStringList( { "sad","sad", "","Sandawe","Sandaweeki" } );
    _languages << QStringList( { "sag","sag","sg","Sango","yângâ tî sängö" } );
    _languages << QStringList( { "sah","sah", "","Yakut","Сахалыы" } );
    _languages << QStringList( { "sai", "", "","South American Indian (Other)" } );
    _languages << QStringList( { "sal", "", "","Salishan languages" } );
    _languages << QStringList( { "sam","sam", "","Samaritan Aramaic","ארמית" } );
    _languages << QStringList( { "san","san","sa","Sanskrit","संस्कृतम्" } );
    _languages << QStringList( { "sas","sas", "","Sasak" } );
    _languages << QStringList( { "sat","sat", "","Santali","ᱥᱟᱱᱛᱟᱲᱤ" } );
    _languages << QStringList( { "scn","scn", "","Sicilian","Sicilianu" } );
    _languages << QStringList( { "sco","sco", "","Scots","Braid Scots" } );
    _languages << QStringList( { "sel","sel", "","Selkup" } );
    _languages << QStringList( { "sem", "", "","Semitic languages" } );
    _languages << QStringList( { "sga","sga", "","Irish, Old (to 900)","Goídelc" } );
    _languages << QStringList( { "sgn", "", "","Sign Languages" } );
    _languages << QStringList( { "shn","shn", "","Shan","ၵႂၢမ်းတႆးယႂ်" } );
    _languages << QStringList( { "sid","sid", "","Sidamo","Sidaamu Afoo" } );
    _languages << QStringList( { "sin","sin","si","Sinhala" } );
    _languages << QStringList( { "sio", "", "","Siouan languages" } );
    _languages << QStringList( { "sit", "", "","Sino-Tibetan languages" } );
    _languages << QStringList( { "sla", "", "","Slavic languages" } );
    _languages << QStringList( { "slo","slk","sk","Slovak","slovenčina" } );
    _languages << QStringList( { "slk","slk","sk","Slovak","slovenčina" } );
    _languages << QStringList( { "slv","slv","sl","Slovenian","slovenski jezik" } );
    _languages << QStringList( { "sma","sma", "","Southern Sami","Åarjelsaemien gïele" } );
    _languages << QStringList( { "sme","sme","se","Northern Sami","davvisámegiella" } );
    _languages << QStringList( { "smi", "", "","Sami languages" } );
    _languages << QStringList( { "smj","smj", "","Lule Sami","julevsámegiella" } );
    _languages << QStringList( { "smn","smn", "","Inari Sami","anarâškielâ" } );
    _languages << QStringList( { "smo","smo","sm","Samoan","Gagana faʻa Sāmoa" } );
    _languages << QStringList( { "sms","sms", "","Skolt Sami","sääʹmǩiõll" } );
    _languages << QStringList( { "sna","sna","sn","Shona","chiShona" } );
    _languages << QStringList( { "snd","snd","sd","Sindhi","سنڌي / सिन्धी / ਸਿੰਧੀ" } );
    _languages << QStringList( { "snk","snk", "","Soninke","Sooninkanxanne" } );
    _languages << QStringList( { "sog","sog", "","Sogdian" } );
    _languages << QStringList( { "som","som","so","Somali","af Soomaali" } );
    _languages << QStringList( { "son", "", "","Songhai languages" } );
    _languages << QStringList( { "sot","sot","st","Sotho, Southern","Sesotho [southern]" } );
    _languages << QStringList( { "spa","spa","es","Spanish" } );
    _languages << QStringList( { "sqi","sqi","sq","Albanian","Shqip" } );
    _languages << QStringList( { "srd","srd","sc","Sardinian","sardu" } );
    _languages << QStringList( { "srn","srn", "","Sranan Tongo" } );
    _languages << QStringList( { "srp","srp","sr","Serbian","српски / srpski" } );
    _languages << QStringList( { "srr","srr", "","Serer","Seereer" } );
    _languages << QStringList( { "ssa", "", "","Nilo-Saharan languages" } );
    _languages << QStringList( { "ssw","ssw","ss","Swati","siSwati" } );
    _languages << QStringList( { "suk","suk", "","Sukuma","Kɪsukuma" } );
    _languages << QStringList( { "sun","sun","su","Sundanese","ᮘᮞ ᮞᮥᮔ᮪ᮓ / Basa Sunda" } );
    _languages << QStringList( { "sus","sus", "","Susu","Sosoxui" } );
    _languages << QStringList( { "sux","sux", "","Sumerian","𒅴𒂠" } );
    _languages << QStringList( { "swa","swa","sw","Swahili","Kiswahili" } );
    _languages << QStringList( { "swe","swe","sv","Swedish","svenska" } );
    _languages << QStringList( { "syc","syc", "","Classical Syriac" } );
    _languages << QStringList( { "syr","syr", "","Syriac","ܠܫܢܐ ܣܘܪܝܝܐ" } );
    _languages << QStringList( { "tah","tah","ty","Tahitian","Reo Tahiti" } );
    _languages << QStringList( { "tai", "", "","Tai languages","ภาษาไท" } );
    _languages << QStringList( { "tam","tam","ta","Tamil","தமிழ்" } );
    _languages << QStringList( { "tat","tat","tt","Tatar","татар теле / tatar tele / تاتار" } );
    _languages << QStringList( { "tel","tel","te","Telugu","తెలుగు" } );
    _languages << QStringList( { "tem","tem", "","Timne","KʌThemnɛ" } );
    _languages << QStringList( { "ter","ter", "","Tereno","Terêna" } );
    _languages << QStringList( { "tet","tet", "","Tetum","Lia-Tetun" } );
    _languages << QStringList( { "tgk","tgk","tg","Tajik","тоҷикӣ / tojikī" } );
    _languages << QStringList( { "tgl","tgl","tl","Tagalog","Wikang Tagalog" } );
    _languages << QStringList( { "tha","tha","th","Thai","ภาษาไทย" } );
    _languages << QStringList( { "tib","bod","bo","Tibetan","བོད་སྐད་" } );
    _languages << QStringList( { "tig","tig", "","Tigre","ትግረ" } );
    _languages << QStringList( { "tir","tir","ti","Tigrinya","ትግርኛ" } );
    _languages << QStringList( { "tiv","tiv", "","Tiv" } );
    _languages << QStringList( { "tkl","tkl", "","Tokelau" } );
    _languages << QStringList( { "tlh","tlh", "","Klingon" } );
    _languages << QStringList( { "tli","tli", "","Tlingit","Lingít" } );
    _languages << QStringList( { "tmh","tmh", "","Tamashek" } );
    _languages << QStringList( { "tog","tog", "","Tonga (Nyasa)","chiTonga" } );
    _languages << QStringList( { "ton","ton","to","Tonga (Tonga Islands)","lea faka-Tonga" } );
    _languages << QStringList( { "tpi","tpi", "","Tok Pisin" } );
    _languages << QStringList( { "tsi","tsi", "","Tsimshian" } );
    _languages << QStringList( { "tsn","tsn","tn","Tswana","Setswana" } );
    _languages << QStringList( { "tso","tso","ts","Tsonga","Xitsonga" } );
    _languages << QStringList( { "tuk","tuk","tk","Turkmen","Türkmençe / Түркменче / تورکمن تیلی تورکمنچ" } );
    _languages << QStringList( { "tum","tum", "","Tumbuka","chiTumbuka" } );
    _languages << QStringList( { "tup", "", "","Tupi languages" } );
    _languages << QStringList( { "tur","tur","tr","Turkish","Türkçe" } );
    _languages << QStringList( { "tut", "", "","Altaic languages" } );
    _languages << QStringList( { "tvl","tvl", "","Tuvalu","Te Ggana Tuuvalu" } );
    _languages << QStringList( { "twi","twi","tw","Twi" } );
    _languages << QStringList( { "tyv","tyv", "","Tuvinian","тыва дыл" } );
    _languages << QStringList( { "udm","udm", "","Udmurt","удмурт кыл" } );
    _languages << QStringList( { "uga","uga", "","Ugaritic" } );
    _languages << QStringList( { "uig","uig","ug","Uighur" } );
    _languages << QStringList( { "ukr","ukr","uk","Ukrainian","українська мова" } );
    _languages << QStringList( { "umb","umb", "","Umbundu","Úmbúndú" } );
    _languages << QStringList( { "und","und", "","Undetermined" } );
    _languages << QStringList( { "urd","urd","ur","Urdu","اُردُو" } );
    _languages << QStringList( { "uzb","uzb","uz","Uzbek","Oʻzbekcha / ўзбекча / ئوزبېچه" } );
    _languages << QStringList( { "vai","vai", "","Vai","ꕙꔤ" } );
    _languages << QStringList( { "ven","ven","ve","Venda","Tshivenḓa" } );
    _languages << QStringList( { "vie","vie","vi","Vietnamese","Tiếng Việt" } );
    _languages << QStringList( { "vol","vol","vo","Volapük" } );
    _languages << QStringList( { "vot","vot", "","Votic","vađđa ceeli" } );
    _languages << QStringList( { "wak", "", "","Wakashan languages" } );
    _languages << QStringList( { "wal","wal", "","Wolaitta" } );
    _languages << QStringList( { "war","war", "","Waray","Winaray" } );
    _languages << QStringList( { "was","was", "","Washo","wá:šiw ʔítlu" } );
    _languages << QStringList( { "wel","cym","cy","Welsh","Cymraeg" } );
    _languages << QStringList( { "wen", "", "","Sorbian languages","Serbsce / Serbski" } );
    _languages << QStringList( { "wln","wln","wa","Walloon","Walon" } );
    _languages << QStringList( { "wol","wol","wo","Wolof" } );
    _languages << QStringList( { "xal","xal", "","Kalmyk" } );
    _languages << QStringList( { "xho","xho","xh","Xhosa","isiXhosa" } );
    _languages << QStringList( { "yao","yao", "","Yao" } );
    _languages << QStringList( { "yap","yap", "","Yapese" } );
    _languages << QStringList( { "yid","yid","yi","Yiddish","ייִדיש" } );
    _languages << QStringList( { "yor","yor","yo","Yoruba","èdè Yorùbá" } );
    _languages << QStringList( { "ypk", "", "","Yupik languages" } );
    _languages << QStringList( { "zap","zap", "","Zapotec","Diidxazá" } );
    _languages << QStringList( { "zbl","zbl", "","Blissymbols" } );
    _languages << QStringList( { "zen","zen", "","Zenaga","Tuḍḍungiyya" } );
    _languages << QStringList( { "zgh","zgh", "","Standard Moroccan Tamazight","ⵜⴰⵎⴰⵣⵉⵖⵜ ⵜⴰⵏⴰⵡⴰⵢⵜ" } );
    _languages << QStringList( { "zha","zha","za","Zhuang" } );
    _languages << QStringList( { "zho","zho","zh","Chinese","中文" } );
    _languages << QStringList( { "znd", "", "","Zande languages" } );
    _languages << QStringList( { "zul","zul","zu","Zulu","isiZulu" } );
    _languages << QStringList( { "zun","zun", "","Zuni","Shiwi'ma" } );
    _languages << QStringList( { "zxx","zxx", "","No linguistic content" } );
    _languages << QStringList( { "zza","zza", "","Zaza" } );
}

QString LanguageList::get(QString id, LanguageIDType from, LanguageIDType to) const
{
    QString undefined = "Undefined";
    if (to == ISO639_3 || to == ISO639_2 ) undefined = "und";
    else if (to == ISO639_1) undefined = "";

    if (id == "") return undefined;

    int f = 0;
    int t = 4;

    if (from == ISO639_1) f = 2;
    else if (from == ISO639_2) f = 0;
    else if (from == ISO639_3) f = 1;
    else if (from == ENGLISH_NAME) f = 3;
    else if (from == NATIVE_NAME) f = 4;

    if (to == ISO639_1) t = 2;
    else if (to == ISO639_2) t = 0;
    else if (to == ISO639_3) t = 1;
    else if (to == ENGLISH_NAME) t = 3;
    else if (to == NATIVE_NAME) t = 4;

    foreach(QStringList lang, _languages)
    {
        if ( f == 4 && lang.count() < 5) continue;

        if (lang[f] == id)
        {
            if ( t != 4 ) return lang[t];
            if ( lang.count() == 5 ) return lang[4];
            return lang[3];
        }
    }
    return undefined;
}

QString LanguageUtils::get(QString id, LanguageList::LanguageIDType from, LanguageList::LanguageIDType to)
{
    return LanguageUtils::languageList->get(id, from, to);
}
